version: '3.1'
services:
  stats-server:
    build: stats/stats-server
    image: stats-server-image
    container_name: stats_server_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explorewithme_stats
      - POSTGRES_DB=explorewithme_stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - EWM_STATS_SERVICE_URL=http://stats-server:9090

  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name:
      stats-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explorewithme_stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: main-service
    image: ewm-main-service
    container_name: ewm-main-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explorewithme
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EWM_STATS_SERVICE_URL=http://stats-server:9090


  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-service-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=explorewithme
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
