DROP TABLE IF EXISTS hits cascade;
DROP TABLE IF EXISTS app cascade;

CREATE TABLE IF NOT EXISTS hits
(
    id  INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    app VARCHAR(255),
    uri VARCHAR(255),
    ip  VARCHAR(45),
    timestamp timestamp without time zone
    );