drop table if exists hits cascade;
drop table if exists app cascade;

CREATE TABLE IF NOT EXISTS hits
(
    id  INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    app VARCHAR(255),
    uri VARCHAR(255),
    ip  VARCHAR(45),
    timestamp timestamp without time zone
    );

CREATE TABLE IF NOT EXISTS app
(
    app_id  INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(255)
    );